server:
  port: 8083

# Complete Spring Configuration Block
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spboot-auth-service
    username: postgres
    password: sisu
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'

  security:
    jwt:
      secret: ${JWT_SECRET:9f8c7a6b5d4e3f2a1b0c9d8e7f6a5b4c9f8c6frb0c9d8e7f6axh7ojngsr14cdbh7a6b5d4e3f2a1b0c9d8e7f6a5b4}
      issuer: ${JWT_ISSUER:com.spboot.auth}
      access-ttl-seconds: ${JWT_ACCESS_TTL_SECONDS:600}
      refresh-ttl-seconds: ${JWT_REFRESH_TTL_SECONDS:86400}
      refresh-token-cookie-name: ${JWT_REFRESH_COOKIE_NAME:refreshToken}
      cookie-secure: ${JWT_COOKIE_SECURE:true}
      cookie-http-only: ${JWT_COOKIE_HTTP_ONLY:true}
      cookie-same-site: ${JWT_COOKIE_SAME_SITE:Lax}
      cookie-domain: ${JWT_COOKIE_DOMAIN:localhost}

      #    oauth2 configurations
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:test-client-id}
            client-secret: ${GOOGLE_CLIENT_SECRET:test-client-secret}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            #/login/oauth2/code/google
            scope:
              - email
              - profile
              - openid
          github:
            client-id: ${GITHUB_CLIENT_ID:test-client-id}
            client-secret: ${GITHUB_CLIENT_SECRET:test-client-secret}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            #/login/oauth2/code/github
            scope:
              - user:email
              - read:user
  jackson:
    serialization:
      write-dates-as-timestamps: false

# Logging
logging:
  level:
    org.springframework.security: DEBUG

app:
  cors:
    front-end-url: http://localhost:5173
  auth:
    frontend:
      success-redirect: http://localhost:5173/oauth/success
      failure-redirect: http://localhost:5173/oauth/failure

#   hikari:
#     pool-name: HikariCP
#     maximum-pool-size: 5
#     connection-timeout: 10000
#     idle-timeout: 600000
#     max-lifetime: 1800000
#     validation-timeout: 1800000
#     leak-detection-threshold: 0
#     initialization-fail-timeout: -1


#System.out.println(UUID.randomUUID().toString().replace("-", ""));
